### ISSUE TITLE
Missing column in PersistedGrant and null pointer exception

### ISSUE THREAD

**Issue by foxbike** [bcgov/vc-authn-oidc#108]
Hi. My controller give me this error:
```
An exception occurred while iterating over the results of a query for context type 
'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'.
Npgsql.PostgresException (0x80004005): 42703: column p.ConsumedTime does not exist.
```

After wallet sending proof succesfully, i also get this error in controller:
```
[13:01:52 DBG] Creating Claims list for presentation record id : test-request-config
[13:01:52 INF] {"Details": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.GetClaims()\n   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.ExecuteAsync(HttpContext context) in /app/VCAuthn/IdentityServer/Endpoints/TokenEndpoint/TokenEndpointResult.cs:line 49\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)", "Category": "Error", "Name": "Unhandled Exception", "EventType": "Error", "Id": 3000, "Message": "Object reference not set to an instance of an object.", "ActivityId": "0HM4I7L89CEJA:00000001", "TimeStamp": "2020-11-27T13:01:52.0000000Z", "ProcessId": 1, "LocalIpAddress": "::ffff:10.129.0.57:8080", "RemoteIpAddress": "35.182.153.45", "$type": "UnhandledExceptionEvent"}
[13:01:52 FTL] Unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.GetClaims()
   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.ExecuteAsync(HttpContext context) in /app/VCAuthn/IdentityServer/Endpoints/TokenEndpoint/TokenEndpointResult.cs:line 49
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
```

I confirm that test-request-config is in the database.

My installation is on Openshift.

**Comment by esune** [comment]
> 
> An exception occurred while iterating over the results of a query for context type 'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'.
> Npgsql.PostgresException (0x80004005): 42703: column p.ConsumedTime does not exist.
I have seen this error before, it appears to be related to IdentityFramework4 trying to purge old expired sessions/grants. I have not (yet) been able to dig deeper and find what the root cause is, however the problem seems benign so far and it does not affect the functionality of `vc-authn` (tested). 

> 
> After wallet sending proof succesfully, i also get this error in controller:
> [13:01:52 DBG] Creating Claims list for presentation record id : test-request-config
> [13:01:52 INF] {"Details": "System.NullReferenceException: Object reference not set to an instance of an object.\n at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.GetClaims()\n at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.ExecuteAsync(HttpContext context) in /app/VCAuthn/IdentityServer/Endpoints/TokenEndpoint/TokenEndpointResult.cs:line 49\n at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)", "Category": "Error", "Name": "Unhandled Exception", "EventType": "Error", "Id": 3000, "Message": "Object reference not set to an instance of an object.", "ActivityId": "0HM4I7L89CEJA:00000001", "TimeStamp": "2020-11-27T13:01:52.0000000Z", "ProcessId": 1, "LocalIpAddress": "::ffff:10.129.0.57:8080", "RemoteIpAddress": "35.182.153.45", "$type": "UnhandledExceptionEvent"}
> [13:01:52 FTL] Unhandled exception: Object reference not set to an instance of an object.
> System.NullReferenceException: Object reference not set to an instance of an object.
> at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.GetClaims()
> at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.ExecuteAsync(HttpContext context) in /app/VCAuthn/IdentityServer/Endpoints/TokenEndpoint/TokenEndpointResult.cs:line 49
> at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
> 
> I confirm that test-request-config is in the database.
> 
> My installation is on Openshift.

Did you submit a credential that met the restrictions? I think this happens when you submit no claims with your proof.

**Comment by foxbike** [comment]
Hum, i have execute successfully the curl -X POST "http://localhost:5000/api/vc-configs" -H "accept: application/json" -H "X-Api-Key: controller-api-key" -H "Content-Type: application/json-patch+json" -d "{ \"id\": \"test-request-config\", \"subject_identifier\": \"email\", \"configuration\": { \"name\": \"Basic Proof\", \"version\": \"1.0\", \"requested_attributes\": [ { \"name\": \"email\", \"restrictions\": [] }, { \"name\": \"first_name\", \"restrictions\": [] }, { \"name\": \"last_name\", \"restrictions\": [] } ], \"requested_predicates\": [] }}" command (not on localhost but on our OpenShift Installation).

Next, i created a schema with email, first_name and last_name attributes and a credential definition on it. Then, i emitted a credential in my wallet with my email, etc. What i'm missing?

**Comment by esune** [comment]
@foxbike what do you see in the mobile wallet and your browser window when you scan the QR code and after you submit your proof? Do you see anything in the agent logs that could provide additional hints?

**Comment by foxbike** [comment]
The mobile wallet asks me to send a proof with the three informations (email, first_name, last_name). I send the requested information and it gives me a success message. The page with the qr code disappears and the keycloak callback url is displayed saying "We are sorry". In the controller log, i see the nullpointer exception on th GetClaims() method (see the first post).

**Comment by foxbike** [comment]
In the gant console, i see the message received after i pushed the send button in wallet: aries_cloudagent.messaging.base_handler INFO Received presentation message: {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/presentation", "@id": "96ae623d-0798-476c-bdc8-cfe3d46b38ba", "~thread": {"thid": "96ae623d-0798-476c-bdc8-cfe3d46b38ba"}, "presentations~attach": [{"@id": "libindy-presentation-0", "mime-type": "application/json", "data": {"base64": "removed for security reason :) see below"}}]}

And the data is: {"proof":{"proofs":[],"aggregated_proof":{"c_hash":"3274897849199856225146482391172509945053726513420886411684452537748014282863","c_list":[]}},"requested_proof":{"revealed_attrs":{},"self_attested_attrs":{"8f10c882-32cb-4dbc-b079-db8635859f52":"LastName","4a8af5be-89fd-4f7c-ad6e-7b65741fbe86":"FirstName","9c4247ab-5fd5-4982-98c3-f5f96c3b3124":"my-email@hotmail.com"},"unrevealed_attrs":{},"predicates":{}},"identifiers":[]}

**Comment by esune** [comment]
Can you try adding restrictions to the proof request to match the name of the schema you are providing? I am wondering if this can be an edge case where not having any restrictions (unlikely to happen in a real scenario) would yield this result.

**Comment by foxbike** [comment]
Yes, restrictions are mandatory!

**Comment by esune** [comment]
Glad we sorted this out! I will look into adding some more documentation and/or potentially handling proof requests without restrictions (if that makes sense).
