### ISSUE TITLE
Can I use this solution to authenticate LDAP or Azure Active Directory users?

### ISSUE THREAD

**Issue by thomas-tran** [bcgov/vc-authn-oidc#117]
Can I use this solution to authenticate LDAP or Azure Active Directory users?

**Comment by swcurran** [comment]
The user to be authenticated must have a verifiable credential.  As such, I think to work with LDAP or AAD those repositories would have to issue a verifiable credential to the user, and then the user would use the VC for authentication using this mechanism.  Alternatively, you can use something like KeyCloak (or equivalent) to provide authentication with LDAP/AAD using an IdP for those, and also provide this as the IdP for users with VCs.

Hope that helps -- I'm not quite certain of the use case, so may have missed the mark.

**Comment by thomas-tran** [comment]
Thanks for the explanation. The use case is the user required to login to
the enterprise application using the azure active directory. I would like
to provide the passwordless to the user  e.g qrcode to login to the
enterprise application or windows.

**Comment by esune** [comment]
@thomas-tran  `vc-authn` acts as OpenID Connect provider for Verifiable Credentials, therefore as @swcurran said you would need an initial step that involves issuing a credential based on AAD attributes, and then accessing your resources by authenticating against `vc-authn`, using the VC that was just acquired.

To obtain the credential you could use something like [issuer-kit](https://github.com/bcgov/issuer-kit.git): the users would authenticate to the issuer web application using their AAD credentials either directly if it can be used in a OIDC flow, or by intergrating AAD as Identity Provider in Keycloak, which is already used/tested in that project.

Protected web applications can then talk to `vc-authn`  - again, either directly or as intergrated IdP in Keycloak, there is an example configuration and docs in this repository - and sign-in using a standard OIDC flow.
For accessing Windows I think I remember [eSatus AG](https://esatus.com) has showed an integration allowing sign-in using a Verifiable Credential, you could check with them.

**Comment by esune** [comment]
Closing the issue, please reopen if more clarifications are necessary.
