### ISSUE TITLE
Mock service for demo is down

### ISSUE THREAD

**Issue by GeroDittmann** [bcgov/vc-authn-oidc#121]
The [DemoInstructions.md](https://github.com/bcgov/vc-authn-oidc/blob/master/docs/DemoInstructions.md) link to a ["mock BC Government service ("Access to Audio")"](https://verified-email-authentication.pathfinder.gov.bc.ca/) that is down:
> Application is not available
> The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

**Comment by esune** [comment]
Thanks for pointing this out. We need to update the link to point to https://verified-email-authentication.vonx.io - we are migrating apps and have not (yet) gone through the process of updating all documentation.
