### ISSUE TITLE
Credential offer error from IIWBook using Trinsic which after ignoring resolves itself to allow further action to be taken

### ISSUE THREAD

**Issue by iamgollum** [bcgov/vc-authn-oidc#126]
Using the trinsic wallet on Iphone, I successfully present my email credential to the IIW service and then received an error notice to which I accepted the option to copy the message to my clipboard:

```
[{"Data":"{\"protected\":\"eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiI1STVodUJNaXp2ZlNIOTZNRU55S2JlVDhQUC1fbjhYcWoxX3l5RGtyZGl6cHNkUGZyR0VkOGcyYnY4N1hDakRnIiwiaGVhZGVyIjp7ImtpZCI6IkFRUnlkTHcySGtEQ1R4anFRZHhpa0M3MVBiN01LcjNYNVdtTW1KSFJtRU5DIiwiaXYiOiJuNG9fX3lnMkdVZ0d5dU03eTVrQ2VjMkg3b1VoNW0yTiIsInNlbmRlciI6IjhKdXFEWjVHVTlMYW1Ha1RZMW5kMnRpb1FBdW5hUWlXbnhQN21qcDRTWFpUcThyLXpIM2lOX2NTWUp6Q2pFR2RVd3VaRjVhWHowekJnLUd5dUllcm8zMnJzdTBYam1lQmIybjJKVEQ2RW9laWlsMVFKLUtmV1FsRjVjWT0ifX1dfQ==\",\"iv\":\"6oJblG9dFkT1sC66\",\"ciphertext\":\"5uaEDvrA06yezULHFG1uNwwbEWLumCXMBqY9BZpkCK3aqJZ_5Bg_SsJTaid6WqKkGLfGu8K9z0PW1zc3TeF-Y6qZ60w3LkEjtJ5hUzoMbkB22O4qfT4rW8SFQ6XhIaM7vQxq1VclBqrNgAz6J5dK41RivYDWYhyOdfOwYhoZ5KUVVHmG8aYZ7wmXqQnqTGmc7ooGVTi2KqNX9oteQRLgboziwa-Loseyxlgx6iboiHFHSsktaTsSKO30QBhFzNLlZGs=\",\"tag\":\"-mSS-QjIK48PyhqLMgUydw==\"}","Timestamp":1617570368,"@id":"a80f354c-2fbb-428a-8259-9bfb7d85bdce","@type":null}]
```

As I had hoped this message is encrypted but it is interesting that I was given the option to do so if I was not given instructions on who to report this too (presumably as they would have the authority / key(s) to decrypt it if necessary). I wonder if I should report this to Trinsic as a UX improvement, assuming this is on their side...? 

Good news is, I then proceeded to the wallet and noticed the pending acceptance offer was in fact there. Then I was able to accept the credential without issue.

**Comment by esune** [comment]
@iamgollum please send this error report/message to Trinsic as it is something on the mobile wallet side. Thanks!
