### ISSUE TITLE
Email/client based restriction in vc-authn

### ISSUE THREAD

**Issue by subhadeep-123** [bcgov/vc-authn-oidc#127]
I have successfully implemented vc-auth, architecture but not the next step of my project I was, I want a specific set of the user to get authentication only. As of now, all users can get authenticated, I want to add restriction here.

**Comment by esune** [comment]
`vc-authn` is an Identity Provider and as such it only provides authentication, not authorization capabilities.

To implement authorization logic you will need to either:
- implement the logic in your app, based on the value of the claims returned in the JWT
- implement the logic in an AIM system such as Keycloak, where `vc-authn` is plugged-in and acts as Identity Provider
