### ISSUE TITLE
Where are we getting user and user.email

### ISSUE THREAD

**Issue by subhadeep-123** [bcgov/vc-authn-oidc#128]
From where are we getting the user var and user.email from???

![image](https://user-images.githubusercontent.com/42332939/116917390-3759a780-ac6c-11eb-9f5b-844e7424be39.png)

@esune

**Comment by esune** [comment]
That is part of Django, see this Stackoverflow answer: https://stackoverflow.com/questions/13713077/get-user-information-in-django-templates

The plugin used to handle authentication ([django-oidc-rp](https://github.com/impak-finance/django-oidc-rp)) plugs directly into the framework and exposes the current authenticated user to Django. I don't believe we use `user.email` anywhere directly, at least not that I can remember.

**Comment by subhadeep-123** [comment]
That worked
