### ISSUE TITLE
How to only use verified credential access

### ISSUE THREAD

**Issue by subhadeep-123** [bcgov/vc-authn-oidc#129]
For my app I only want to use verified credential access, so can I stop the keycloak service to ask from username and password

![image](https://user-images.githubusercontent.com/42332939/117845123-e5cda000-b29d-11eb-8743-2bca1dc9fa64.png)

**Comment by subhadeep-123** [comment]
Also, this is happening before the redirection to the controller, I want my app/keycloak service to directly redirect to the controller and load the QR code... @esune .

**Comment by esune** [comment]
Using Keycloak you would specify a couple of additional parameters in your OIDC adapter configuration:
- `pres_req_conf_id` tells the `vc-authn` controller which proof-configuration to use to generate the proof-request
- `kc_idp_hint` tells Keycloak to send the request directly to a specific IdP, in your case it will be the one you registered for `vc-authn`
[This](https://github.com/bcgov/ised-business-banking-initiative/blob/main/openshift/templates/issuer-web/config/bcreg-registration/dev/config.json#L25-L26) is an example configuration that provides both parameters.

You can also authenticate directly against `vc-authn` bypassing Keycloak completely, you just need to tweak your OIDC authentication settings. You can see an example in the demo django app, another configuration example is [here](https://github.com/bcgov/essential-services-delivery/blob/master/openshift/templates/issuer-web/config/esr1/dev/config.json#L14-L36).

**Comment by subhadeep-123** [comment]
I read your answer but that did help in this case, I am trying to disable Keycloak SSO and only want to show IDP's QR code for the users to scan...

![Screenshot_20210513-174304_Chrome](https://user-images.githubusercontent.com/42332939/118124306-0703cd00-b413-11eb-9412-d10bac200f2a.jpg)

I am using is repo vc-auth, but I want when the client clicks on the authenticate button, I only want to show them the QR code i.e, I want to disable the SSO of keycloak and only let External IDP do its job...

I have taken help from here but this was not useful.
https://stackoverflow.com/questions/61570607/how-to-disable-the-sso-feature-in-the-keycloak#:~:text=1.,new%20flow%2C%20click%20Save.%22

This is really important for the app I'm working on.

If you need any extra info I can share the client configuration.

PS:- I am using browser workflow in authentication.

**Comment by esune** [comment]
As I already mentioned, you will want to add the `kc_idp_hint` query parameter to your authentication request.

Documentation for the query parameter is [here](https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/identity-broker/suggested.adoc).

An example configuration of a browser flow that uses the `kc_idp_hint` to route requests directly to `vc-authn` is [here](https://github.com/bcgov/ised-business-banking-initiative/blob/main/openshift/templates/issuer-web/config/bcreg-registration/dev/config.json#L25-L26).

**Comment by subhadeep-123** [comment]
Hello @esune I took your suggestion, and the problem was solved, but another thing that I need to bypass, is that after the credential is verified Keycloak is asking for updated account information. I tried many things but I cannot bypass this page also.

Here I am attaching an image for your convenience.

![Screenshot_3](https://user-images.githubusercontent.com/42332939/118467069-1a6bac80-b721-11eb-8298-7fe9b121e063.png)
 
This is the last step for me, any help will be really appreciated.

**Comment by esune** [comment]
You will need to tweak your Keycloak settings to prevent it from updating the user profile on first broker login flow. The [Keycloak docs](https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/identity-broker/first-login-flow.adoc) should have some details.

**Comment by subhadeep-123** [comment]
I am using browser flow, will it work this way too?

**Comment by esune** [comment]
The first broker login is trigger after the browser flow is initiated, so yes.

**Comment by subhadeep-123** [comment]
This worked, we needed to set the  Update Profile on First Login to OFF in Review Profile(review profile config) , First Broker Login.
Thank you very much for your help man.
