### ISSUE TITLE
Error when running manage start 

### ISSUE THREAD

**Issue by pranavkirtani88** [bcgov/vc-authn-oidc#130]
for controller-db  Cannot start service controller-db: driver failed programming external connectivity on endpoint vc-authn-oidc_controller-db_1 (bce5da213f86718b0eacbcf17e45adf404a2de31562cb416e6587be9f688a287): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

The above error is thrown and I am unable to proceed, i dont have any other ports occupied outside of what is in the script and VON network.

**Comment by swcurran** [comment]
I think 5432 is a Postgres port usually.  Do you have another postgres Docker container running?

**Comment by pranavkirtani88** [comment]
No, only a local VON network and this repo.

**Comment by pranavkirtani88** [comment]
Found it, sorry my bad, there was another non dockerized instance of postgres running.

**Comment by swcurran** [comment]
Not sure what it is, but something is using the port normally used by Postgres.  Looks like in running the script you can set the database port to something else by doing:

```
DATABASE_PORT=5432 ./manage ...
```

Where you pick some other port than 5432 since it is in use.
