### ISSUE TITLE
Error While building vc-auth controller on CentOS

### ISSUE THREAD

**Issue by rajgohel89** [bcgov/vc-authn-oidc#133]
I cloned git repo and executed

` ./mange buld ` but failing at 6th step.

**Error**
```
/usr/share/dotnet/sdk/3.1.413/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.jon. [/app/VCAuthn.sln]
/usr/share/dotnet/sdk/3.1.413/NuGet.targets(128,5): error :   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed ou after 100000ms. [/app/VCAuthn.sln]
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

```

**Tried Solution**
* Created NuGet.config file with proxy url under `/usr/share/dotnet/sdk/3.1.413` but didn't helped.

**NuGet.Config File**

```
<configuration>
	<config>
		<add key="http_proxy" value="url" />
		<add key="https_proxy" value="url" />
	</config>
</configuration>
```

**Comment by rajgohel89** [comment]
@esune Thanks for sharing the details. I'm able to build and start containers. 
I'm getting Nutanix login page instead of swagger-ui while accessing `http://localhost:5000`

**Comment by esune** [comment]
Did you remove the `NuGet.Config` file? You should not have it in your repository.
Nutanix is not part of `vc-authn` so it must be an issue with your overall proxy settings.

**Comment by rajgohel89** [comment]
I couldn't find it. Where I can see it.

**Comment by esune** [comment]
>
> 
> **Tried Solution**
> 
>     * Created NuGet.config file with proxy url under `/usr/share/dotnet/sdk/3.1.413` but didn't helped.
> 
> 
> **NuGet.Config File**
> 
> ```
> <configuration>
> 	<config>
> 		<add key="http_proxy" value="url" />
> 		<add key="https_proxy" value="url" />
> 	</config>
> </configuration>
> ```

You mentioned creating a NuGet file, this is what I was referring to. It might not be relevant anyway if you can complete the build.
Please check what other services you have running on your machine that might be responding on port `5000`, it looks like your requests are being directed to the website you mentioned, which is not used in `vc-authn-oidc` so I am unable to provide meaningful help unfortunately.

**Comment by rajgohel89** [comment]
Oh Okay. i have deleted Nuget.config file.
i tried` ./manage build` and `./manage start`
still getting Nutanix login page.
I have verified no other services running on `PORT 5000`

**Comment by esune** [comment]
Other than checking for custom entries on your `hosts`file I am unfortunately not sure what to suggest. This seems like an issue related to your specific machine/network setup, not the project.

**Comment by rajgohel89** [comment]
Yea tried on a new computer. I can access Swagger-ui.

I configured attributes with the below request.
`    curl -X POST "http://localhost:5000/api/vc-configs" -H "accept: application/json" -H "X-Api-Key: controller-api-key" -H "Content-Type: application/json-patch+json" -d "{ \"id\": \"test-request-config\", \"subject_identifier\": \"email\", \"configuration\": { \"name\": \"Basic Proof\", \"version\": \"1.0\", \"requested_attributes\": [ { \"name\": \"email\", \"restrictions\": [] }, { \"name\": \"first_name\", \"restrictions\": [] }, { \"name\": \"last_name\", \"restrictions\": [] } ], \"requested_predicates\": [] }}"

Mobile wallet(Trinsic) showing invalid QR code.
`

**Comment by esune** [comment]
The restrictions array for each attribute should be non-empty, see here: https://github.com/bcgov/vc-authn-oidc/issues/108#issuecomment-736553056

Unfortunately mobile wallets do not seem to handle correctly self-attested attributes (attributes without restrictions). You can add restrictions to match a credential you have in your wallet. See [here](https://github.com/bcgov/vc-authn-oidc/blob/master/demo/presentationRequest.json) for a proof-request configuration with restrictions that should match the credential issued by the [BC Gov Email Verification](https://email-verification.vonx.io/) service.
