### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by oznfc** [bcgov/vc-authn-oidc#138]
I am getting this error before and after scanning the qr code. Successful I present proof.
```GET http://localhost:5000/vc/connect/poll?pid=a643fc4a-4289-4252-a057-f57fece5bb76 400 (Bad Request)```

**Comment by esune** [comment]
This is expected, it means no proof-request response was received and it will return a 400 until one is received and a record is created on the vc-authn agent wallet. See https://github.com/bcgov/vc-authn-oidc/issues/134
