### ISSUE TITLE
Something wenr wrong

### ISSUE THREAD

**Issue by oznfc** [bcgov/vc-authn-oidc#139]
after the clicked "present" button , ı'm getting this error.  

![error](https://user-images.githubusercontent.com/39590206/141111848-6636adfd-d102-49d0-986a-ee6b531175df.JPG)

**Comment by esune** [comment]
Can you try with a different wallet?
Can you also please confirm whether the proof-configuration contains restrictions? If it doesn't, .net wallets do not work correctly with self-attested attributes as far as I know (see https://github.com/bcgov/vc-authn-oidc/issues/106#issuecomment-890918794).

**Comment by oznfc** [comment]
ı tried with lissi . it's error : ```proof culdn't send```. 
I'm triying with local network. Actually I runned von + email verfication +oidc.  I also connect the wallet to the local network.  I verified e-mail and added my mobile wallet(trinsic).  
```
"restrictions": [
            {
              "schema_name": "verified-email",
              "issuer_did": "8kZ4xs6rPzp9DPMrmVtuNE"
            }
          ]
```

**Comment by esune** [comment]
If you got the credential from the hosted `email-verification` service this will likely not work, since you're going to be trying to verify the credential on a network/ledger that is different than the source (Sovrin StagingNet).

Additionally, there is currently an issue with `ngrok` and LetsEncrypt certificates that breaks the SSL handshake between the mobile wallet and the agent (see #135 ).

**Comment by oznfc** [comment]
I'm using local node for everything. I connected to local from my all app(mmobile-wallet / email verification / oidc). I'm going step by step. I can verify without  restrictions . ```State is verified.``` 
 but ı have error on my page ```unexpected error when authenticating with idendity provider. ```

it's console error logs 
```
[08:43:11 DBG] Client validation success
controller_1      | [08:43:11 INF] {"ClientId": "keycloak", "AuthenticationMethod": "SharedSecret", "Category": "Authentication", "Name": "Client Authentication Success", "EventType": "Success", "Id": 1010, "Message": null, "ActivityId": "0HMD8RH43SGA2:00000006", "TimeStamp": "2021-11-16T08:43:11.0000000Z", "ProcessId": 9, "LocalIpAddress": "::ffff:192.168.48.6:80", "RemoteIpAddress": "31.223.51.97", "$type": "ClientAuthenticationSuccessEvent"}
controller_1      | [08:43:11 DBG] Constructing token result for session : 2b995e6d-04dc-4c24-a268-ed62031e19c2
controller_1      | [08:43:11 DBG] Constructing token result
controller_1      | [08:43:11 DBG] Generating token for audience : keycloak
controller_1      | [08:43:11 DBG] Creating Claims list for presentation record id : verified-email
controller_1      | [08:43:11 INF] {"Details": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.GetClaims()\n   at VCAuthn.IdentityServer.Endpoints.TokenEndpoint.TokenEndpointResult.ExecuteAsync(HttpContext context) in /app/VCAuthn/IdentityServer/Endpoints/TokenEndpoint/TokenEndpointResult.cs:line 49\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)", "Category": "Error", "Name": "Unhandled Exception", "EventType": "Error", "Id": 3000, "Message": "Object reference not set to an instance of an object.", "ActivityId": "0HMD8RH43SGA2:00000006", "TimeStamp": "2021-11-16T08:43:11.0000000Z", "ProcessId": 9, "LocalIpAddress": "::ffff:192.168.48.6:80", "RemoteIpAddress": "31.223.51.97", "$type": "UnhandledExceptionEvent"}

```

**Comment by oznfc** [comment]
I'm using Lissi wallet because ``` something went wrong``` error contuine on trinsic. I'm not using qr code . I'm  clicked "open in a trusted wallet"  after the shared ngrok url to my phone. I  proofing this way on lissi wallet.

**Comment by oznfc** [comment]
I solved .
Disable the expired root certificate in the trust store of the device (_Settings->Biometrics & security->Other security settings->View security_ certificates and disable "DST root ca x3")```

**Comment by esune** [comment]
Tanks for the feedback! It looks like it was definitely related to #135/#137 then.
