### ISSUE TITLE
Base64-encoded presentation requests should be uri encoded

### ISSUE THREAD

**Issue by amanji** [bcgov/vc-authn-oidc#140]
When extracting the the base64-encoded presentation request from an expanded url obtained from the service, `+` characters are converted to whitespaces which invalidates the base64 string.

For example the following url is read from storage:

`https://3e46-2001-569-73bb-3f00-585d-7b9b-da28-56f7.ngrok.io?m=eyJAaWQiOiI4ZmUwZTM3Mi04MjU1LTQxNDQtYjc5OC00MDAzZDNiOTQ0MWQiLCJAdHlwZSI6ImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL3ByZXNlbnQtcHJvb2YvMS4wL3JlcXVlc3QtcHJlc2VudGF0aW9uIiwicmVxdWVzdF9wcmVzZW50YXRpb25zfmF0dGFjaCI6W3siQGlkIjoibGliaW5keS1yZXF1ZXN0LXByZXNlbnRhdGlvbi0wIiwibWltZS10eXBlIjoiYXBwbGljYXRpb24vanNvbiIsImRhdGEiOnsiYmFzZTY0IjoiZXlKdVlXMWxJam9pZG1WeWFXWnBaV1F0WlcxaGFXd2lMQ0p1WVcxbGN5STZiblZzYkN3aWRtVnljMmx2YmlJNklqRXVNQ0lzSW01dmJtTmxJam9pT1RRME5EUTJNemcxTURZM01qTTNOVFU1TVRjME5ESXdJaXdpY21WeGRXVnpkR1ZrWDJGMGRISnBZblYwWlhNaU9uc2lNalpsWkRNM09HWXRaall5WkMwME5UYzNMVGc0T1RFdE1qRmtOVE0zWlRoak0yUXlJanA3SW01aGJXVWlPaUpsYldGcGJDSXNJbkpsYzNSeWFXTjBhVzl1Y3lJNlczc2ljMk5vWlcxaFgyNWhiV1VpT2lKMlpYSnBabWxsWkMxbGJXRnBiQ0lzSW1semMzVmxjbDlrYVdRaU9pSk5WRmx4YlZSQ2IweFVOMHRNVURWU1RtWm5Tek5pSW4xZGZYMHNJbkpsY1hWbGMzUmxaRjl3Y21Wa2FXTmhkR1Z6SWpwN2ZYMD0ifX1dLCJjb21tZW50IjpudWxsLCJ`**+**`c2VydmljZSI6eyJyZWNpcGllbnRLZXlzIjpbIkZZbW9GdzU1R2VRSDdTUkZhMzdka3gxZDJkWjN6VUY4Y2tnN3dtTDdvZk40Il0sInJvdXRpbmdLZXlzIjpudWxsLCJzZXJ2aWNlRW5kcG9pbnQiOiJodHRwczovLzg2NWItMjAwMS01NjktNzNiYi0zZjAwLTU4NWQtN2I5Yi1kYTI4LTU2Zjcubmdyb2suaW8ifX0=
`

The query param is extracted as:

`eyJAaWQiOiI4ZmUwZTM3Mi04MjU1LTQxNDQtYjc5OC00MDAzZDNiOTQ0MWQiLCJAdHlwZSI6ImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL3ByZXNlbnQtcHJvb2YvMS4wL3JlcXVlc3QtcHJlc2VudGF0aW9uIiwicmVxdWVzdF9wcmVzZW50YXRpb25zfmF0dGFjaCI6W3siQGlkIjoibGliaW5keS1yZXF1ZXN0LXByZXNlbnRhdGlvbi0wIiwibWltZS10eXBlIjoiYXBwbGljYXRpb24vanNvbiIsImRhdGEiOnsiYmFzZTY0IjoiZXlKdVlXMWxJam9pZG1WeWFXWnBaV1F0WlcxaGFXd2lMQ0p1WVcxbGN5STZiblZzYkN3aWRtVnljMmx2YmlJNklqRXVNQ0lzSW01dmJtTmxJam9pT1RRME5EUTJNemcxTURZM01qTTNOVFU1TVRjME5ESXdJaXdpY21WeGRXVnpkR1ZrWDJGMGRISnBZblYwWlhNaU9uc2lNalpsWkRNM09HWXRaall5WkMwME5UYzNMVGc0T1RFdE1qRmtOVE0zWlRoak0yUXlJanA3SW01aGJXVWlPaUpsYldGcGJDSXNJbkpsYzNSeWFXTjBhVzl1Y3lJNlczc2ljMk5vWlcxaFgyNWhiV1VpT2lKMlpYSnBabWxsWkMxbGJXRnBiQ0lzSW1semMzVmxjbDlrYVdRaU9pSk5WRmx4YlZSQ2IweFVOMHRNVURWU1RtWm5Tek5pSW4xZGZYMHNJbkpsY1hWbGMzUmxaRjl3Y21Wa2FXTmhkR1Z6SWpwN2ZYMD0ifX1dLCJjb21tZW50IjpudWxsLCJ c2VydmljZSI6eyJyZWNpcGllbnRLZXlzIjpbIkZZbW9GdzU1R2VRSDdTUkZhMzdka3gxZDJkWjN6VUY4Y2tnN3dtTDdvZk40Il0sInJvdXRpbmdLZXlzIjpudWxsLCJzZXJ2aWNlRW5kcG9pbnQiOiJodHRwczovLzg2NWItMjAwMS01NjktNzNiYi0zZjAwLTU4NWQtN2I5Yi1kYTI4LTU2Zjcubmdyb2suaW8ifX0=`

The base64-encoded presentation request should be uri encoded prior to formatting/storing the expanded url, such that when the query parameter is later extracted, encoded characters are not converted to spaces.

**Comment by amanji** [comment]
Looking for some discussion on this from perhaps @esune or @swcurran

**Comment by swcurran** [comment]
Are you sure that using Base64URL encoding won't just work?  I did the following tests on a [Base64 Encode/Decode](https://www.base64decode.org/) site:

- decode the URL above (with the "+") and decoded (worked)
- encode the result using base64 and got the same result (with the "+")
- encode the result using base64URL and the "+" was now a "-", which is safe for URL use.
- decoded the result and got the correct result, verified by re-encoding it.

Is it not possible to just use base64URL encoding of the original content?  That should have been used in the first place.

Thanks

**Comment by swcurran** [comment]
"Is it not possible" -- meaning will that work with the existing mobile agents.
