### ISSUE TITLE
İdenty Server connection

### ISSUE THREAD

**Issue by oznfc** [bcgov/vc-authn-oidc#142]
Can ı connect to my identyserver from another app  for  login ?if ı can, how ?

**Comment by esune** [comment]
What do you mean exactly with this, can you please clarify what you are trying to achieve?

**Comment by oznfc** [comment]
This repo has demo we can login by credentials.     i want to write react peoject like this examples. Can i connect my project to this oidc for verify credintials without keycloak?

**Comment by swcurran** [comment]
Yes -- Keycloak is an example of an IAM that can be used for this. Other IAMs could be used (e.g. Forge Rock, etc.), and an OIDC Relying Party library can be used without an IAM.

**Comment by esune** [comment]
> This repo has demo we can login by credentials. i want to write react peoject like this examples. Can i connect my project to this oidc for verify credintials without keycloak?

This is an example of a configuration used by `oidc-js` (in our case through `vuex-oidc` to authenticate directly against `vc-authn`: https://github.com/bcgov/essential-services-delivery/blob/main/openshift/templates/issuer-web/config/healthbc/dev/config.json#L14-L26

Any OIDC client can be used to authenticate directly, if you check the demos you'll see how to do that in a python app as an example (that is NOT going through Keycloak). The Keycloak config is an example of how to integrate `vc-authn` as IdP in an SSO system.
