### ISSUE TITLE
Polling interval time reducing for better user experiance

### ISSUE THREAD

**Issue by sheraliinamdar** [bcgov/vc-authn-oidc#168]
Hi team, 
    During verifying the credentials, in background polling is happening for every 20 secs. However in class constructor default value i can 
see as 10000msec. can some please help me understand from where that polling interval 20 sec is coming ?.  From user perspective view, 
taking around 25 seconds for verification may not be the good user experience.  where can i reduce that polling time ?

Thank you!

**Comment by WadeBarnes** [comment]
The setting is here; https://github.com/bcgov/vc-authn-oidc/blob/main/oidc-controller/src/VCAuthn/appsettings.json#L6

**Comment by esune** [comment]
Closing, please reopen if necessary.
