### ISSUE TITLE
Service bug in step: VC Authentication OIDC (vc-authn-oidc): Demo Deployment - Proceed button doesn't render

### ISSUE THREAD

**Issue by kentbull** [bcgov/vc-authn-oidc#170]
The https://verified-email-authentication.vonx.io/ site does not allow the "Proceed" button to be clickable.
Upon pulling up the inspector there appears to be a problem with the Vue installation or configuration:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/65027257/167267384-ab3f5850-e072-4044-aade-429c49145ea7.png">

**Comment by WadeBarnes** [comment]
@esune, Thoughts?

**Comment by swcurran** [comment]
@amanji -- perhaps you might take a look at this one, as it appears to be a Vue issue.

**Comment by esune** [comment]
It looks like the Vue app is not being loaded (`Vue is not defined`). It might be because the cdn links are resolving a different versions of Vue, we had the problem before where they were targeting `latest` and the switch from Vue 2 to Vue 3 broke the UI.

**Comment by swcurran** [comment]
@amanji -- def over to you if you have the time.  Don't know if bumping to 3 is the best or what is the right thing.  Please take a look when you get a chance.  Thanks!

**Comment by esune** [comment]
@amanji was this ever addressed? I don;t think so based on commit history, but wanting to confirm.

**Comment by amanji** [comment]
I don't believe it was either

**Comment by esune** [comment]
This doesn't appear to be an issue anymore after testing, closing.
