### ISSUE TITLE
What happens when IdentityServer4 reaches end of support

### ISSUE THREAD

**Issue by DibbsZA** [bcgov/vc-authn-oidc#171]
I have read that the support for IdentityServer4 will be discontinued when dotnet core 3.1 support is ended in 6 months?
IdentityServer as project has now been take over by [Duende](https://duendesoftware.com/), but this is now a licensed product.

**Comment by swcurran** [comment]
Thanks for the heads up -- much appreciated. We're thinking about simply replacing IdentityServer4, which is an OAuth 2.0 and OpenID Connect provider, with another open source implementation in the same category.  Any opinions on that idea?  Any suggests of (more or less) equivalent open source options?

**Comment by esune** [comment]
See #181
