### ISSUE TITLE
Credential verification is getting successful if anyone attribute is matching

### ISSUE THREAD

**Issue by sheraliinamdar** [bcgov/vc-authn-oidc#173]
Hi Team, 
   In vc-auth component, When we configured the credential attributes like Name , Email and SPOC_Email in the holder app, if user 
is having **any one attribute among above three**, then credentials are getting verified successfully. I want it to be successful ONLY if all three attributes are present.  Below is the example configuration in VC auth

{"name":"verified-email","version":"1.0","requested_attributes":[{"name":"Name","restrictions":[{"issuer_did":"Uv1xWZPjxA4E5Q66juavTx"}]},{"name":"Email","restrictions":[{"issuer_did":"Uv1xWZPjxA4E5Q66juavTx"}]},{"name":"SPOC_Email","restrictions":[{"issuer_did":"Uv1xWZPjxA4E5Q66juavTx"}]}]}

**Comment by swcurran** [comment]
To clarify in closing this -- `names` requires that the three attributes must come from the same credential. `name` is present for backwards compatibility, but we suggest that you always using `names`.
