### ISSUE TITLE
IdentityServer4 EOL November 2022

### ISSUE THREAD

**Issue by PaulWen** [bcgov/vc-authn-oidc#181]
According to the official [IdentityServer4 Docs](https://identityserver4.readthedocs.io/en/latest/) IdentityServer4 will only be maintained with security updates until November 2022. Are there any plans to migrate to the [IdentityServer5/Duende](https://duendesoftware.com/products/identityserver) implementation?

**Comment by swcurran** [comment]
More likely we will replace IdentityServer with a new OIDC provider implementation.  As we understand, that software is not open source.  We are looking for recommendations of open source implementations to use as a replacement. We are unlikely to stay with .NET in this component.

**Comment by esune** [comment]
As per @swcurran response above, we are looking at switching the architecture to use a different implementation that will not rely on IdentityServer - the initial work is being pushed to the `2.0-development` branch.

Closing this issue for now, tracking for the new work will be added to the repo in the coming days/weeks.
