### ISSUE TITLE
Remove requirement for Keycloak

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#197]
The current release of `vc-authn` can be used both independently and as IdP connected to an AIM solution (e.g.: keycloak).

`vc-authn` 2.0 should keep this functionality, and remove the hard dependency on Keycloak.

This will require the implementation of configuration settings (e.g.: authorized clients) and standard OpenID endpoints including the `.well-known/openid-configuration` discovery endpoint, the JWKS endpoint exposing public keys, etc.

----

OpenID certified libraries that could be helpful for this task: https://openid.net/developers/certified/

**Comment by Jsyro** [comment]
#230 should have provided all the requirements, but has not been tested yet.
