### ISSUE TITLE
Update manage script to be more wizard-like

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#210]
The `manage` script is meant to be a helper used to start the project, and should be as simple and automated as possible.

Some improvements to look into:
- [ ] Prompt to decide whether to use a multi-tenant agent, or the default dedicated instance
- [ ] If the multi-tenant configuration cannot be programmatically inferred, add prompts to collect it
- [ ] Execute `wallet_init.py` when necessary
- [ ] More? Assess what needed.

**Comment by loneil** [comment]
Possibly consider a note in the readme for Windows about WSL or Git Bash or any of the other ways to run a bash script, as if someone on Windows just pulls the repo and follows the instructions it won't run for them in powershell or cmd.

**Comment by esune** [comment]
First pass is completed, closing issue. New enhancements to be logged as separate tasks.
