### ISSUE TITLE
SPIKE- Proof-request Configuration Explorer

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#226]
UI tool to search/discover proof-requests that have already been registered in VC AuthN.

Needs some brainstorming, might be a candidate for GrapQL to drill-down into existing proof configurations.

Acceptance Criteria:
Investigate the current state and draft a HackMD document with recommendations describing what approach would be recommendable, and what should be implemented to achieve the desired outcome.

**Comment by hiteshgh** [comment]
carry fwd but will be done by EOW June 2

**Comment by Gavinok** [comment]
https://hackmd.io/@7FYPe91BSb6SKH2doI3PpQ/BkACcwNFn

Above is the proposed specification. Let me know what you think might need to change or any improvements to it.

@esune @amanji

**Comment by amanji** [comment]
LGTM!
