### ISSUE TITLE
Auth Page Styling

### ISSUE THREAD

**Issue by hiteshgh** [bcgov/vc-authn-oidc#253]
Review and improve the UI/UX of the page used to display the QR Code and authenticate with vc-authn.

Work to be completed off the `2.0-development` branch.
Authorization page code is located in this file: [oidc-controller\api\routers\oidc.py](https://github.com/bcgov/vc-authn-oidc/blob/7e86a3a693fd3c84c773e90063344d50a4a7ef38/oidc-controller/api/routers/oidc.py).
It looks like there are some hard-coded values that should not be there (see line [53](https://github.com/bcgov/vc-authn-oidc/blob/7e86a3a693fd3c84c773e90063344d50a4a7ef38/oidc-controller/api/routers/oidc.py#L53)).

Current look-and-feel of the auth page:
![image](https://user-images.githubusercontent.com/2395873/231234018-b6ceda0a-e992-4017-91cc-16b8e4aa2076.png)
Old UI page code is [here](https://github.com/bcgov/vc-authn-oidc/blob/6c77a2d5a798c9da9f26bc29ed5c09e7a0417c73/oidc-controller/src/VCAuthn/Views/Authorize/Authorize.cshtml).

I think we want to keep the UI/UX consistent with the existing one, but checking-in with a designer (maybe @knguyenBC ) might be a good idea in case there are recommendations/suggestions.

**Comment by knguyenBC** [comment]
I'll be happy to take on the UX/UI work for this.

**Comment by esune** [comment]
Thanks @knguyenBC! @popkinj and I will connect and coordinate 🙂 

One more thought: since `vc-authn` is not a BCGov-only product, it would be nice if we can use some basic theming on the page to select colors/images for each running instance.

**Comment by esune** [comment]
@knguyenBC, @popkinj and myself synced-up today:
- we'll start with restoring the auth page to the current look-and-feel, with some improvements
  - include i18n functionality based on user's language from the browser
  - add refresh button with instructions to "refresh page and try again" if proof request fails to verify

@knguyenBC will provide UI wireframes for the next iteration, with additional improvements such as possible (TBD based on QR library support) QR code branding, improved wording to mitigate users trying to scan the QR code with a regular mobile camera.
