### ISSUE TITLE
Unable to see QR Code

### ISSUE THREAD

**Issue by cvarjao** [bcgov/vc-authn-oidc#257]
It is reproducible when accessing ACM from BCGN network
<img width="468" alt="image002" src="https://user-images.githubusercontent.com/1348549/230180522-75745041-f4b1-4116-a318-cdd61815fc52.png">

**Comment by esune** [comment]
@cvarjao are you aware of any "special" characteristics of the BCGN network that might need to be taken into account while troubleshooting?

**Comment by cvarjao** [comment]
> @cvarjao are you aware of any "special" characteristics of the BCGN network that might need to be taken into account while troubleshooting?
> 
> `vc-authn` 1.0 is using `unpkg` and `polyfill.io` as cdn to fetch the JS/CSS resources for the QR code page (see [here](https://github.com/bcgov/vc-authn-oidc/blob/main/oidc-controller/src/VCAuthn/Views/Authorize/Authorize.cshtml)): I wonder if BCGN is blocking those requests.

I am not aware of anything special that would cause this. I am sure BCNGN has several special/security characteristics though. I am not familiar with the details though.

**Comment by WadeBarnes** [comment]
This appears to be a DNS issue with some government networks.  We've seen this in development on the ACM (A2A) side when we have to connect to the government networks through VPN to do some of the work.  I've talked with @nikola-rados about this issue and provided some direction on how to troubleshoot with @atfrench.

**Comment by jleach** [comment]
I can replicate the LSBC error when using private browsing mode. My current hypothesis is as follows: When connecting to BCNGN, it installs a certificate for a network appliance that essentially performs a man-in-the-middle attack. This is done to scan network traffic for malware. The SSL issue likely arises because the connection's SSL is terminated and then re-encrypted with a different certificate.

[screen shot](https://fullboarca-my.sharepoint.com/:i:/g/personal/jason_leach_fullboar_ca/EQgnJYaURelPnBf_EiOVzosBhUs4db5Y3F7YKWYLHX2cbQ?e=R2MGLm)

**Comment by WadeBarnes** [comment]
@nikola-rados, @atfrench, Have a look at what @jleach posted above.

**Comment by jleach** [comment]
@WadeBarnes FYI I think I was mostly right above. I installed the proper certificate for our security appliance called "IDIR Infrastructure Authority3.cer" and manually updated the "trust" in my Keychain to "Allow for SSL" now this site works fine and I see the QR code. I think when you authenticate with BCNGN for WiFi this cert should be automatically installed - maybe I said "nope"? In any case, this was the fix.

**Comment by WadeBarnes** [comment]
Thanks for the update @jleach.  We've got the security group looking at these results since it's affecting more and more users, including folks using government machines.  So it would seem the certificate is not distributed consistently.

**Comment by WadeBarnes** [comment]
@jleach, we should compare the certs used for BCNGN WiFi and direct VPN to see if they are different.

Here are the details of the one encountered using VPN:

![image](https://user-images.githubusercontent.com/10504350/235147385-1ca9ae48-638b-4fbe-a18e-7f21d50b51bb.png)

**Comment by WadeBarnes** [comment]
The certificate in your keychain is the `IDIR Infrastructure Authority3` CA certificate for the one I listed above.

![image](https://user-images.githubusercontent.com/10504350/235198940-1c9ffa0a-49b3-492b-be4c-5e7fbfcdcd44.png)

**Comment by WadeBarnes** [comment]
Seems like a workaround is to export and install that certificate, but that does not make for a great user experience.  I'd like to know what the network and security ops folks say about this.

cc @nikola-rados

**Comment by jleach** [comment]
@NickCorcoran Might know some people who can better help with that level of questions.

AFAIK its just a machine scanning data streams for malware. That cert only comes on gov machines and would need to be purposely installed by lawyers.

**Comment by NickCorcoran** [comment]
I believe that for gov workstations, the cert is installed on Windows machines by default.  Mac users have to do a little more as they are more self-managed.  I will bring this up w/ our security/networking teams.

**Comment by WadeBarnes** [comment]
Thanks @NickCorcoran

**Comment by jleach** [comment]
I'll test next time I'm in the office.

**Comment by WadeBarnes** [comment]
@jleach,  When you do the test, please capture the network traffic as you did before.  We want to see how the journey changes, if at all.

**Comment by jleach** [comment]
@WadeBarnes I tested a few times on DOGWOOD-NGN (the new DOGWOOD). Both the QR code and https://unpkg.com/ work. I confirmed by deleting the certificate and testing both again on BCNGN and they fail as expected.

**Comment by WadeBarnes** [comment]
Great!  Thanks @jleach.  Now we know we're dealing with a small subset of users who have IDIR accounts, connect to BCNGN, and are using non-government issued laptops.

**Comment by esune** [comment]
@WadeBarnes do we need to keep this issue open still, or can we consider it done?
