### ISSUE TITLE
Copy QR Code for mobile users.

### ISSUE THREAD

**Issue by popkinj** [bcgov/vc-authn-oidc#295]
This use case if for users that have come to the QR Code within their phone web browser.

The common workflow for mobile users is to screen shot a QR Code. Then upload to a digital wallet. This may not be obvious to all users.

We could provide a button or something that allows users to download the svg/png to their phone, or favorite photo app.

Open to suggestions from the team. 🤔

**Comment by esune** [comment]
I think we will have to wait for a better standardization of the `didcomm://` prefix for this: iOS and Android handle deep-links very differently, and while in the past we had a button on the authentication screen, it hasn't really worked consistently.

Once deeplinking (or whatever mechanism is exposed by the OS) is fixed, then we can add that feature. Adding a way to screenshot and share the QR code seems less than user friendly to me, and would not want to encourage it.

**Comment by swcurran** [comment]
A proposal has been put forth in the Aries community to work around the lack of a useful iOS deeplinks feature.  James Ebert presented “Community Selector" last week at the Aries Working Group meeting.  Not sure if we want to jump on this, but worth looking at to see if we want to help with pushing this out in the community.

The recording for the meeting is here https://youtu.be/ieXRj-5dp_8, with the demo/discussion in the early part of the meeting.

**Comment by esune** [comment]
I took a quick look at the video, it is an interesting approach. I will watch again as I need/want to understand a bit better how it works, what I am mostly concerned about is that things are changing in both iOS and Android (based on a talk I was at at the last IIW) and this problem may be resolved a different way, natively, with a standard API exposed by both OS systems. There are questions on this still, and I don;t really have any more recent information to provide feedback at this time.

**Comment by popkinj** [comment]
Thanks @swcurran, I'll have a look at the video as well.
I'm starting to be hopeful that Apple is coming around to play ball. Their latest release of Safari (17) actually has good support for PWAs. :open_mouth:
