### ISSUE TITLE
API Scheduler for fulfilling timeouts.

### ISSUE THREAD

**Issue by popkinj** [bcgov/vc-authn-oidc#298]
Each proof request has a [time_out](https://github.com/bcgov/vc-authn-oidc/blob/2.0-development/oidc-controller/api/authSessions/models.py#L21-L22) for when a proof becomes expired. The proof doesn't actually get labelled as expired until there is a request for the status of the proof [here](https://github.com/bcgov/vc-authn-oidc/blob/2.0-development/oidc-controller/api/routers/oidc.py#L38-L58).

It would be a lot cleaner if we could complete remove the polling end point and replace it with some kind of scheduler that would handle expired proofs. Open to suggestions. 🤔

**Comment by swcurran** [comment]
Is this something that should be built into ACA-Py?  The same thing came up around connection establishment time outs. As I recall, the timeouts are created via a decorator in the message.

**Comment by popkinj** [comment]
> 

Absolutely @swcurran . If we could receive a webhook notification when a proof expires that would solve all our problems.

**Comment by esune** [comment]
+1 to having ACA-Py be able to send webhooks for these type of decorated events. Currently `vc-authn` is NOT using the decorator on the proof-request payload as far as i can remember, but it would make sense to switch over to using that rather than having a custom solution that would require development and maintenance.

**Comment by swcurran** [comment]
Yes — I was thinking the same thing.  A webhook for the timeout.

Here is the decorator that I think would be used [RFC 0032: Message Timing](https://github.com/hyperledger/aries-rfcs/tree/main/features/0032-message-timing), and the “expires_time” item.

**Comment by esune** [comment]
There is one edge scenario I am not sure the decorator would help us with: we want to visually indicate the proof-request expired in the QR code page as soon as we get past the expiry time. With the decorator, we'd only know that the proof-request expired once a response is received (I think), which could potentially be after the proof expiry time.
Example.: I load-up the auth page, the QR code/proof will expire in 1 minute, I respond to a phone call and come back after 1 minute. Iedally I would see the QR code page indicating the proof expired already, but if we (only) use the decorator I would still be able to respond and I would then be told the proof expired. A bit of a UX question.
