### ISSUE TITLE
Update chart readme

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#300]
Acceptance Criteria 

Update chart readme to be Bitnami-style, as already completed for Traction (see https://github.com/bcgov/traction/blob/2c6e437cddf1b4aac24ac1e0af12ba3cdbbdc6fe/charts/traction/README.md)

**Comment by swcurran** [comment]
I'm not sure it is a good idea to document all of the ACA-Py startup parameters in each Helm chart, as in the example linked in the Acceptance Criteria.  Any chance there is a good way to document them/enable their use once in ACA-Py, and then reference where ever they are needed -- Helm charts, docker compose startups, etc.  The startup configs in ACA-Py are adjusted regularly, and we need a way to manage the (way too many!) options. Or at least, when we update a Helm Chart or docker compose configuration to use a new version, we pull in the new version of ACA-Py configuration settings.

Likewise, we need a way to document document the configuration parameter/environment variables that are used on top of ACA-Py and in a deployment.  Particularly important are the ports, and the common parameters that are shared across components -- e.g. the configuration parameters for a database that also have to be known to the components that are clients of the database.

It would be nice to have a clear view of where the list of settings can be found, and where overrides can be set, for the two deployment models we have -- Helm Charts and docker compose.

**Comment by esune** [comment]
The Helm chart documentation will be only for the services specifically maintained in the repository - in this case the `vc-authn` controller. We will not be documenting all ACA-Py options here, but it will likely be a task for when we push an "official" ACA-Py chart to be used as a dependency (in which case the chart would live in ACA-Py's repo).

**Comment by swcurran** [comment]
I was more talking about the example linked in the acceptance criteria.  The Traction Helm Chart looks like it has all of the ACA-Py config points documented.

**Comment by esune** [comment]
Ah, gotcha. In the case of Traction we will have to see how to decouple the ACA-Py chart - I am not yet sure about it. The issue in that case is that Traction is an ACA-Py plugin and therefore the cart needs to run a modified version of ACA-Py. It should be easier for VC-AuthN since it's a "plain" agent running in read-only mode.
