### ISSUE TITLE
Redirect for BC Wallet not working on the V2.0 branch

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#304]
I have a setup on my system running for v2.0 with the demo app.  When I scan the QR code I get an "invalid QR Code" message on BC Wallet (bad). When I scan it with the camera, the "You didn't use a real Wallet" screen (good). However, I notice that when I look at the redirect URL for the "You didn't use a real Wallet".  How can I get this to work with BC Wallet? I tried several other wallets and saw the same type of issue -- it didn't work.

Other notes:

- I don't see the query parameter that the wallet would need, containing the presentation request. When the redirection to the "you didn't use a real wallet" was implemented, was the query parameter dropped?  Normally, the browser would use the URL and ignore the query parameter, while the Wallet would do the reverse.  Is it intentional that the query parameter is not seen in the browser, and if so, how is that done?
- My setup uses public routes (not ngrok) for all of the components -- keycloak, agent, controller and demo app. Happy to show you what I have adjusted in the docker compose/environment variable setup for that.

**Comment by swcurran** [comment]
You can try it yourself -- all defaults and https://vcauthn.cloudcompass.ca, https://vcauthn-agent.cloudcompass.ca, https://vcauthn-kc.cloudcompass.ca, https://vcauthn-app.cloudcompass.ca.  The presentation request is configured to use the Verified Email Credential.

**Comment by swcurran** [comment]
Good news -- @esune was able to get this work.  He was on 1.0.9 (978) Android, whereas I'm on 1.0.10 (1098) IOS, so the guess is that it is the wallet that is the issue.  Closing this issue.

**Comment by swcurran** [comment]
Not good news. Whenever I try it, it doesn't work.  I've reinstalled the BC Wallet to go back to 1.0.9 and it is still not working.

@jleach @wadeking98  -- fyi. Any other suggestions of what I can try?  The QR was new and definitely not reused.

**Comment by swcurran** [comment]
@popkinj -- is there a way to query the controller to see what shortened URLs are available?  Or see what is going on?

**Comment by esune** [comment]
@swcurran are you on wifi or mobile data when you are home and trying to connect? I tried again, I can scan the QR code successfully and present my credential - it won't redirect, but I suspect this might be something we fixed in a more recent version (make sure you have pulled and built the latest 2.0-development ranch). I am suspecting a network issue as it works for me and not for you on the same instance...

**Comment by swcurran** [comment]
Yes, I was thinking something like that and was going to have to try it from my device. But I think I already know what it is. Network crap. Sigh. Trying again.

**Comment by swcurran** [comment]
Yup...that was it. Sorry about that.  All good.

@WadeBarnes -- one day I'll figure out what's up with my firewall rules. Doh!!!
