### ISSUE TITLE
Once the QR code is displayed, getting errors about redirecting to an HTTP URL instead of HTTPS

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#305]
Getting this error in the browser console after displaying the QR code:

```

polling-xhr.js:157 Mixed Content: The page at 'https://vcauthn.cloudcompass.ca/authorize?scope=openid+vc_authn&state=e7talf-ZzwoIgGRXj38VSAIQNtQeNRXDJ23hILk8Pqs.N2urmTGRxg4.vue-fe&response_type=code&client_id=keycloak&redirect_uri=https%3A%2F%2Fvcauthn-kc.cloudcompass.ca%2Fauth%2Frealms%2Fvc-authn%2Fbroker%2Fvc-authn%2Fendpoint&pres_req_conf_id=verified-email&nonce=84xanuk8oRtvLUsSUp6twA' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://vcauthn.cloudcompass.ca/ws/socket.io/?EIO=4&transport=polling&t=OctRXz9'. This request has been blocked; the content must be served over HTTPS.
```

To see this, open your browser console and navigate to: https://vcauthn-app.cloudcompass.ca and click “Secure”. The message begins appearing.

FYI @esune

**Comment by swcurran** [comment]
Arrghh…it didn’t take my content.

On navigating to the “Secure” screen with the QR code, the following message comes up in the console:

```

polling-xhr.js:157 Mixed Content: The page at 'https://vcauthn.cloudcompass.ca/authorize?scope=openid+vc_authn&state=e7talf-ZzwoIgGRXj38VSAIQNtQeNRXDJ23hILk8Pqs.N2urmTGRxg4.vue-fe&response_type=code&client_id=keycloak&redirect_uri=https%3A%2F%2Fvcauthn-kc.cloudcompass.ca%2Fauth%2Frealms%2Fvc-authn%2Fbroker%2Fvc-authn%2Fendpoint&pres_req_conf_id=verified-email&nonce=84xanuk8oRtvLUsSUp6twA' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://vcauthn.cloudcompass.ca/ws/socket.io/?EIO=4&transport=polling&t=OctRXz9'. This request has been blocked; the content must be served over HTTPS.
```

To replicate, go to: https://vcauthn-app.cloudcompass.ca and then click “Secure”, with the browser console open.

**Comment by popkinj** [comment]
I may have found the solution to this @swcurran . It would be handy if I could test it in an https setup. Is your cloudcompass environment something I could get access to? Otherwise I can add the fix to my branch and you could implement that.

**Comment by swcurran** [comment]
If you put the fix into a PR — or just let me know what to do, I can apply it. Not easy to give you access to it.
