### ISSUE TITLE
Proof-request expires before CONTROLLER_PRESENTATION_EXPIRE_TIME has passed

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#323]
After deploying the `dev` instance of VC-AuthN (https://vc-authn-oidc.apps.silver.devops.gov.bc.ca) with `CONTROLLER_PRESENTATION_EXPIRE_TIME=300`, proof-requests that have been initiated are expired after a few seconds instead of waiting for the set timeout.

**Comment by popkinj** [comment]
This seems to be working now. I was able to test the Websocket.... Which was a bit of a question mark within the Openshift environment. The result was almost instant.

![Screenshot from 2023-09-18 14-03-42](https://github.com/bcgov/vc-authn-oidc/assets/479074/892d4cf1-5812-492e-aae6-40e9a87c0920)

The setting in Dev is for 300sec (5min).

![Screenshot_20230918_140510_Clock](https://github.com/bcgov/vc-authn-oidc/assets/479074/cfcab921-b94f-4643-855c-c0a34737d5bc)

**Comment by esune** [comment]
Odd, the app was expiring the QR code right away until recently - now it seems to have it stick around for the desired amount of time. Closing as it does not seem to be an issue anymore.
