### ISSUE TITLE
Improve logging [2.0]

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#332]
Logging in Vc-AuthN 2.0 is a bit lackluster: if something goes wrong, it is hard to pinpoint exactly where the issue is being raised from. Do a pass-through of the code and improve log statements to be more helpful/complete.

**Comment by jamshale** [comment]
There's some type of bug or problem with the setup of oidc-controller preventing the global error handler from getting any details of unhandled exceptions.
This is quite a important problem to solve. It's going to make solving any type of production issue take a lot longer to fix..
I'm going to assign myself and try and figure it out when developing unit tests
