### ISSUE TITLE
Chart releaser action does not detect changes when triggered by tag/release

### ISSUE THREAD

**Issue by i5okie** [bcgov/vc-authn-oidc#342]
When chart-releaser action is run in a workflow triggered by a `tag`, or `release`, the action fails.
Chart-releaser fails to compare the file changes.

Example:
```
Run helm/chart-releaser-action@v1.5.0
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since 'v2.0.0-beta2'...
Nothing to do. No chart changes detected.
```

An existing issue exists: https://github.com/helm/chart-releaser-action/issues/150
A PR exists with proposed changes that have not been approved/merged as of today: https://github.com/helm/chart-releaser-action/pull/154

**Comment by esune** [comment]
Resolved by #343
