### ISSUE TITLE
Add backwards-compatibility setting for token claims

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#347]
A major shift from VC-AuthN 1.0 is the introduction of the `vc_presented_attributes` to wrap the presented attributes into one object and avoid the need to know ahead of time the claim names used for a proof-request and create named mappers.

As a migration step from 1.0 to 2.0, however, we want to introduce a compatibility setting that will still allow named mappers to work and allow a transition period for client applications to adapt to the new pattern.

Token generation is handled in the [get_claims}(https://github.com/bcgov/vc-authn-oidc/blob/1e3ec9234d9ebb5f9c4201fb7d40d96a264b04fd/oidc-controller/api/core/oidc/issue_token_service.py#L34) method. It should be updated to add ALL presented attributes as named claims at the root of the token.

Suggesting using `USE_V1_COMPATIBILITY` as flag to be set to `true`/`false`.

Examples for a proof request resulting in `city` and `province` being shared, the expected token should look as follows:
- when  `USE_V1_COMPATIBILITY=false`
```json
{
  ...
  "vc_presented_attributes": {
    "city": "Victoria",
    "province": "BC"
  }
}
```
- when `USE_V1_COMPATIBILITY=true` (note the extra token claims)
```json
{
  ...
  "vc_presented_attributes": {
    "city": "Victoria",
    "province": "BC"
  },
  "city": "Victoria",
  "province": "BC"
}
```

**Comment by esune** [comment]
The changes in the PR look great and match what requested. As discussed yesterday with @jamshale, however, I am starting to think we might want to add this setting at the `ver_config` level, rather than global.

The reason is to disincentivize using the "old" token structure, and leave it *ONLY* where extremely necessary (i.e.: ACM while migrating the code), rather than blanket-applying it to everyone and potentially cause confusion.

@jamshale I believe we both thought that changing the code to take a parameter - defaulting to `false` when not provided - that is stored at the verification-config level would not be complicated. Could you confirm?

@WadeBarnes picking your brain here as well from an operations perspective: would you prefer having a globally-applied setting that is used for ALL proof-requests, or a configuration-specific one? Keep in mind that, with our integration with the SSO Pathfinder team, all (most) new apps using VC-AuthN would go through that IdP integration that only supports the new standard claims (`pres_req_conf_is` and `vc_presented_attributes`).

**Comment by WadeBarnes** [comment]
@esune, I'd prefer the configuration-specific one.

**Comment by jamshale** [comment]
@esune Sounds good. I can change that. It shouldn't be a problem.

**Comment by esune** [comment]
Thanks @jamshale , sorry for the change in plans, but it seems indeed like it would be a better option.

**Comment by esune** [comment]
Changes approved and merged
