### ISSUE TITLE
Tweaks to logo on QR code page

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#398]
Update BCGov logo in QR code page to conform to standard.

**Comment by popkinj** [comment]
Changing this:
![Screenshot from 2023-12-06 10-19-40](https://github.com/bcgov/vc-authn-oidc/assets/479074/0d2268f1-d261-436c-a60f-71fc38d2c3c4)

To this:
![Screenshot from 2023-12-06 10-35-35](https://github.com/bcgov/vc-authn-oidc/assets/479074/f839d61b-ae6c-49f8-8278-a8ed93922727)

I tweaking the spacing a touch as well.
