### ISSUE TITLE
which wallet to use?

### ISSUE THREAD

**Issue by japrescott** [bcgov/vc-authn-oidc#41]
following the instructions under `demo` and configuring my setup to use `http://test.bcovrin.vonx.io` as the ledger, I am able to present a QR code "to initiate the Verifiable Credential exchange". However, using the streetcred app it says its an invalid QR code (I have a credential from Email Verification Service).

Which wallet should I be using and which DIDComm protocol(s) does the wallet need to support to complete the flow outlined by vc-authn-oidc?

**Comment by japrescott** [comment]
I was able to get the demo to work with the streetcred app by additionally setting the `IDENTITY_SERVER_URL` and `AGENT_ENDPOINT` variables to the appropriate ngrok urls.

**Comment by swcurran** [comment]
Nice.  Is there something we can do to improve the docs?  Thanks

**Comment by japrescott** [comment]
hey @swcurran .
It would be good to take my learnings about the above variables and add it to the documentation that they need to be set as well.

my cmd to start `vc-authn-oidc/docker`;
`NGROK_CONTROLLER_URL=${tunnel5000} 
 IDENTITY_SERVER_URL=${tunnel5000} NGROK_AGENT_URL=${tunnel5679} AGENT_ENDPOINT=${tunnel5679} LEDGER_URL=http://test.bcovrin.vonx.io ./manage start`

my cmd to start `vc-authn-oidc/demo/docker`;
`NGROK_CONTROLLER_URL=${tunnel5000} IDENTITY_SERVER_URL=${tunnel5000}  AGENT_ENDPOINT=${tunnel5679} LEDGER_URL=http://test.bcovrin.vonx.io ./manage start`

since I've got you here stephen :) which is your preferred wallet that supports using your own genesis file (to test one own von-network?)
btw. great edX course you put together 👍

**Comment by swcurran** [comment]
Thanks - very cool.  We'll look at that.

When we need to use a wallet, we make sure we are using the BCovrin test ledger and use Streetcred (as you did above). Right now its the only way. We have a person that has done a bunch of work on OSMA and it might be an option soon.  Devs also use ACA-Py for testing when they want to test interactions, but being on mobile is not crucial.

**Comment by swcurran** [comment]
Where are the `tunnel5000` et. al. env variables coming from?

**Comment by japrescott** [comment]
They represent the URI that by default is localhost:[someport]. In a real deployment thats yourdomain.com:[someport].

In my case since its running locally on my machine (and need to access from outside), I am using `ngrok`, which creates a tunnel to my local machine so you can access them from outside.

**Comment by swcurran** [comment]
I know about ngrok - I was wondering about the variables themselves.  Did you create them earlier in the process?  Does ngrok create them?  I looked in the ngrok docs and didn't see anything about them.

**Comment by japrescott** [comment]
no, sorry for the misunderstanding
I just named them that way so its clear which value from ngrok needs to be inserted

**Comment by swcurran** [comment]
Got it - thanks!
