### ISSUE TITLE
Responsive sizing for VCAuthn login page on mobile devices

### ISSUE THREAD

**Issue by loneil** [bcgov/vc-authn-oidc#420]
Placeholder, to expand here. The page seems to just shrink on mobile devices due to fixed sizing. Things get quite small

Ex:
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/d137df85-0c43-441e-a23e-2b7ebe923dbd)

**Comment by swcurran** [comment]
My $0.02CDN: On a mobile device we don’t want to show the VC-Authn-OIDC QR code (can’t scan it) — just the deep link URL.  Makes size the problerm go away.

**Comment by loneil** [comment]
That's the plan, but the box is still going to be super small then and stuff like "don't have a BC Wallet" and the link and header text are super shrunk. The issue is the page is designed to shrink to a fixed size.

rough example at 100% scale:
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/da6d42ed-717b-44ed-8dfe-c01df7afe35d)

**Comment by knguyenBC** [comment]
There still needs to be a way to present the QR code on a mobile device in the small chance that people do wish to open the wallet from a different device. That chance of happening is probably super low so the button to present the QR code doesn't have to be super visible. A secondary or even tertiary button design should suffice.

**Comment by loneil** [comment]
Agree, something like below (text, style TBD) that exposes the QR code again is what I've got going

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/fa670542-ddeb-4def-868d-eaaec66a17ab)

**Comment by loneil** [comment]
Can start on this once https://github.com/bcgov/vc-authn-oidc/issues/413 is completed and in
