### ISSUE TITLE
Update the start scripts to pick up the ngrok URLs vs. having to set them

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#43]
As mentioned in issue #41 (comment - https://github.com/bcgov/vc-authn-oidc/issues/41#issuecomment-589124626) see about updating the start script to automagically pick up the ngrok URLs.

This is a bit of bash playing based on some parsing of ngrok data that @esune has done elsewhere in the app.  He'll get to it when he gets a chance, or someone else could grab it and ping him for getting started pointers.

**Comment by esune** [comment]
This is resolved in #45
