### ISSUE TITLE
Switch to using embedded Vue app for QR Code page

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#432]
The QR code page is fairly simple, and was therefore developed with plain JS. This is however causing challenges with the handling of websockets, among other things, as they are being interrupted when the phone switches to BC wallet from the browser (deep-linking scenario).

using an embedded Vue app will allow us to improve handling of these events without relying on custom code, as well as allow for future enhancements/improvements.

c.c.: @loneil @Gavinok

**Comment by esune** [comment]
Example: old VC-AuthN authorize page https://github.com/bcgov/vc-authn-oidc/blob/v1.0.0/oidc-controller/src/VCAuthn/Views/Authorize/Authorize.cshtml

**Comment by esune** [comment]
One thing to check-out while restructuring the app using Vue: when BC Wallet scans the QR Code, in some scenarios (i.e.: using OOB) the QR code scans, but BC Wallet says it is invalid and doesn't move forward. At that point, it's a dead-end in VC-AuthN since there is no way to refresh the page (other than refreshing through the browser) and the proof-request will not timeout as the QR code was scanned. We may want to add a control to start over the process in these scenarios, like the refresh control that appears when the proof has expired.

**Comment by loneil** [comment]
Yeah good call, some sort of "Taking too long? Try again" status display on a (longer) timer or something.

**Comment by esune** [comment]
> Yeah good call, some sort of "Taking too long? Try again" status display on a (longer) timer or something.

Yes, that would take care of that scenario AND potentially others with similar interaction patterns

**Comment by Gavinok** [comment]
Sounds good I'll add that now. Thanks for the ideas!
