### ISSUE TITLE
Flake linting doesn't appear to fail steps on pull requests

### ISSUE THREAD

**Issue by loneil** [bcgov/vc-authn-oidc#476]
The Link with Flake8 step on PRs looks like it's passing when there are errors and warnings being thrown 

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/48ef7c7d-d483-48f4-a48f-137a17e41875)

**Comment by loneil** [comment]
The Lint stage in the action has this set intentionally. Not sure if a specific reason?

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/c4af6c4a-247f-45b5-9514-e0347b97908a)

@Jsyro any chance you remember if this is needed to workaround anything?

**Comment by Jsyro** [comment]
No clue, I would have moved or copied that from a different project...... 

feel free to change if desired.

**Comment by loneil** [comment]
Resolved in https://github.com/bcgov/vc-authn-oidc/pull/484
