### ISSUE TITLE
Add a way to return to service page

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/vc-authn-oidc#485]
**### User story**
As a user, I want a way to return back to the service page from vc-authn page, so that I can easily go back to the service page if I decide to not not continue sharing my information, I decide to decline the proof request, if the proof request was rejected or an error occurred.

### Acceptance Criteria
- Add a "Return to service" button that takes people back to the service page

**Comment by loneil** [comment]
Question about capabilities: https://stackoverflow.developer.gov.bc.ca/questions/1240

and some discussion: https://chat.developer.gov.bc.ca/channel/sso?msg=nha9LiEGKbWxjrPHj
