### ISSUE TITLE
Delete old/expired authsessions

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#511]
For each authentication event (i.e.: QR code generated) by VC-AuthN, an AuthSession is created and stored in `mongodb` to track the state of authentication. This can lead to bloating of the database as more and more authentication requests are initiated.

In particular, AuthSessions that either expire or become "orphaned" because the webpage is reloaded will contribute to this phenomenon.

We need a way to automatically prune:
* sessions that reach the expired state
* sessions that are superseeded by a new one
* sessions that are older than a certain age (i.e.: over two weeks old, regardless of their state)

**Comment by loneil** [comment]
Also referenced here: https://github.com/bcgov/vc-authn-oidc/issues/424

**Comment by esune** [comment]
> Also referenced here: #424

I swear I searched for the issue as i knew we had logged something, and didn't find it...
Thanks!

**Comment by esune** [comment]
Closing as duplicate of #424
