### ISSUE TITLE
Can scan a QR code while it's in Pending state

### ISSUE THREAD

**Issue by loneil** [bcgov/vc-authn-oidc#520]
The mask over the QR code does not obscure it enough to prevent (at least the BC Wallet) from attempting to scan it as a QR code. This can have unintended consequences it seems (depending on BC Wallet build/OS can result in Invalid QR code, or an attempt to do the proof that doesn't work)

This mask should probably obscure the QR code more?

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/995f3ba3-07cc-4b65-bfac-aea4fd99174c)

**Comment by loneil** [comment]
For example, on Android (1707) doing multiple scans and then denying the one that comes up can result in:

![Screenshot_20240515-164003](https://github.com/bcgov/vc-authn-oidc/assets/17445138/7fd19566-8008-4437-8a5f-466c460db7ff)

**Comment by loneil** [comment]
Don't have the issue on "Refresh" state as the text box blocks more

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/9c593b21-4c2a-4d68-a263-13e60c545dd2)

**Comment by knguyenBC** [comment]
Adding an opaque border around the "QR code scanned" will make it look like a button that people may click. I would suggest blurring the QR code. Also, there's a transparency treatment on the text as well, that should be removed.

**Comment by esune** [comment]
@loneil if the effort is not significant let's implement Kim's recommendations before we close the issue.

**Comment by loneil** [comment]
Changes in https://github.com/bcgov/vc-authn-oidc/pull/540
QR is lighter and unscannable. Text is normal opaque text now so no button confusion
