### ISSUE TITLE
Update Helm chart to support TTL index creation

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#539]
#531 introduced a mechanism to set-up an optional TTL index in mongo that purges old records after they "expire". The default behaviour is to not have a TTL set-up, but we will want to have these settings in the Helm chart for ease of deployment.

**Comment by loneil** [comment]
We presently don't have the TTL index in DEV VCAuth-N (no Helm vals for CONTROLLER_SESSION_TIMEOUT_CONFIG_FILE)

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/bfc803bc-7c5e-4486-98d8-7c8ab1a09ccb)
