### ISSUE TITLE
Pydanctic .dict() depcrecation warnings

### ISSUE THREAD

**Issue by loneil** [bcgov/vc-authn-oidc#544]
Places using the Pydantic models and `.dict()` show a warning

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/84e15dbd-5f79-40ee-a651-87d5ed6d9921)
 
Can(?) I think just replace like:
```
response = client.create_presentation_request(ver_config.generate_proof_request())
pres_exch_dict = response.model_dump()
```

**Comment by esune** [comment]
Resolved in #658
