### ISSUE TITLE
CDN problems in FE pages

### ISSUE THREAD

**Issue by loneil** [bcgov/vc-authn-oidc#547]
On **non-government** devices running on **BCNGN** (not Dogwood) there is a known certificate problem (not going into it here) that blocks certain web traffic.

CDNs that deliver CSS and JS assets needed are blocked.

It's likely best to not use the CDNs.

**Comment by esune** [comment]
Self-hosting the static assets seems to be the easiest/simplest way forward - for now. Will re-assess whether to introduce a more complex build process for the frontend in the future.

**Comment by loneil** [comment]
Have this deployed to VCAuth-N dev and I'm able to do things on my contractor laptop on BCNGN in the lab

![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/d0ecb827-cc1f-4651-849c-4ae98641ea3d)

**Comment by esune** [comment]
I think we can close this, changes will be pushed to test/prod as soon as we do a new release.
