### ISSUE TITLE
Return strucured claims in JWT

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#62]
On a successful authentication event, `vc-authn` returns a JWT contaninig all the claims used to fulfill the presentation request. The claims are all returned at the root level of the JWT, making it impossible to distinguish which credentials they are coming from especially when multiple claims using the same name were provided (e.g.: multiple `issued` dates from different credentials/schemas).

Example of "flat" payload:
```
{
  "sub": "1234567890",
  "given_name": "John",
  "family_name": "Doe",
  "issued_date": ["1970-01-01", "2000-01-01"]
  "iat": 1516239022
}
```

To resolve this, it would be good to return the claims in a structured object named after the schema they belong to.

Example of "structured" payload:

```
{
  "sub": "1234567890",
  "demographics": {
      "given_name": "John",
      "family_name": "Doe"
   },
   "epoch": {
       "issued_date": "1970-01-01"
   },
   "y2k": {
       "issued_date": "2000-01-01"
   }
  "iat": 1516239022
}
```

**Comment by esune** [comment]
It looks like the above idea is not possible: the credential structure returned by the agent to the controller in a webhook does not expose which credential/schema the claim is coming from, so it is not possible to group simple claims based on that.

Claims requested using a restriction defined by using the `names` array can be grouped together, however it will still not be possible to know which credential/schema the group of claims belongs to.

I am not sure it is worth continuing much further right now, as it would require for the best case scenario to have both grouped and ungrouped claims together, forcing clients to check both rather than follow the same pattern for any claim when retrieving information from the id token.

I will close the issue for now, it can be re-opened in the future if the underlying infrastructure will allow for claims to be returned in a structured form by the agent.

**Comment by swcurran** [comment]
What is handing the values back that is NOT providing that information?  Indy/ACA-Py/vc-Authn?  I think that is likely something we need to look at.  I think we need to make sure that the verifier gets back information to make a further assessment about whether it is willing to accept the issuer.  In the example I gave on the call today -- we accept data from a "Verified Person Schema", but only if the Issuer is in a given group.

Not urgent but something we need to consider as we think of the interaction model.

**Comment by esune** [comment]
It is aca-py: the webhook payload sent back to the controller once the credential is verified contains the list of `requested_attributes` in the proof and the proof itself:
```
...
"requested_attributes": {
            "ef05d809-767f-4e1b-9c10-1617e428dd30": {
                "names": [
                    "Given Name",
                    "Surname"
                ],
                "restrictions": [
                    {
                        "schema_name": "Schema 1",
                        "schema_version": "1.0.0",
                        "issuer_did": "abcdefghilmno"
                    },
                    {
                        "schema_name": "Schema 2",
                        "schema_version": "1.0.0",
                        "issuer_did": "qwertyuioljdf"
                    }
                ]
            },
            "requested_predicates": {},
            "nonce": "761764877744881075508395"
        }
...
"requested_proof": {
                    "revealed_attrs": {},
                    "revealed_attr_groups": {
                        "ef05d809-767f-4e1b-9c10-1617e428dd30": {
                            "sub_proof_index": 0,
                            "values": {
                                "Surname": {
                                    "raw": "John",
                                    "encoded": ...                                },
                                "Given Name": {
                                    "raw": "Doe",
                                    "encoded": ...
                                }
                            }
                        },
                        "self_attested_attrs": {},
                        "unrevealed_attrs": {},
                        "predicates": {}
                    }

```
_Note:_ the above is an example of proof using the `names` array. If non-grouped claims are present, there would be a similar data structure to the one displayed above in both sections, but for each one of the claims.

As you can see, the most I can assert from the above is that:
- all claims come from the same credential
- the credential respects the restrictions, and is matches one of the two schemas
I cannot determine whether the credential used was for `Schema 1` or `Schema 2`.

When working with individual claim restrictions (not using `names` array) this complexity explodes: as stated above, each individual claim would have a data section in both `requested_attributes` and `requested_proof.revealed_attrs` that allows the controller to assert the value is indeed respecting the restrictions being imposed, but it will not allow further "processing".

The service from your example would come before we even get to the proof, as the proof-request itself should be generated with restrictions to allow only credentials from specific issuers. Once the proof-request is processed, there is - as of now - no way to reassemble that information.

I am not sure what the implications of adding that data to a proof in aca-py/Indy are, but I think - for this use-case - it should be handled at that level before/while processing the proof.
