### ISSUE TITLE
Add human-readable proof-request information to QR code page

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#646]
When presented with the QR code to scan with BC Wallet, users will NOT know until after scanning it what is requested in the proof.

To improve this, we should add a `metadata` object to the proof-configuration that can be used to hold information about the proof (useful also for searching in a list) with information about what is requested.

The page would display a section similar to the following (example for the Lawyer + Person credential proof):
The proof request will ask you to prove the following:
- That you are a BC Resident
- That you are a member of the Law Society of British Columbia

The data structure containing the information to be displayed could be something like:
```json
{
 "ver_config_id":"accredited-lawyer-bcpc",
  ...,
  "metadata": {
    "proved_claims": ["That you are a BC Resident", "That you are a member of the Law Society of British Columbia"]
  }
}
```

Note: `i18n` descriptions could be added to accomodate for multi-language systems.

**Comment by WadeBarnes** [comment]
Standard items in metadata should also be `title` and `description`, which, when provided, could be displayed in place of the current `Scan with a Digital Wallet` title to provide additional context.

**Comment by loneil** [comment]
Would we want "Scan with a Digital Wallet" (and "Continue with:" on mobile) to be able to be changed to something else? As it's instructional UX for the wallet usage.

So with a configurable
- title
- description
- claims

There would be options like this (size and layout TBD). Might be worth getting input from @knguyenBC 


![image](https://github.com/user-attachments/assets/5e09c2a1-b8a5-4b64-a6c5-cedbe8b9313e)



![image](https://github.com/user-attachments/assets/af9b3530-b343-416b-8afa-942b0622464a)

**Comment by WadeBarnes** [comment]
Yes, where the layout and content default to what we see on the screen currently.

In the absence of metadata content:
- `Title` defaults to "Scan with Digital Wallet".
- `Description` default to "".
- `Claims` defaults to "".

**Comment by knguyenBC** [comment]
Can the metadata be configured for every use case or is it configured for every proof request? i.e. in the courthouse example above, the description is specific to courthouse materials but if another use case uses the same proof, could the description change?

Even though we have that screen for when people scan with a normal camera, I think it's important to  call out "scan with a digital wallet" to catch them a earlier (a reward for people who read). So I agree with the screens @loneil has suggested. The issue is who is defining the Title, description, and claims.

**Comment by WadeBarnes** [comment]
Current thought is the meta-data would be defined on the proof request.  But yes that needs to be considered when registering the proof request; how generic is it's use.

**Comment by esune** [comment]
The metadata will be for each proof-request configuration. Any user of VC-AuthN can decide to use any of the configured proof-requests, so the title/description should be as generic as possible (for that proof-request).

That is the reason why I was suggesting we start with the list of claims, as this can be used to fill a parametrized statement that will always be applicable regardless of the proof-request in use.

**Comment by knguyenBC** [comment]
I think for now, the list of claims and title is fine. No need for a description as that should be defined by the verifier on their own webpage. I'm not sure where the title will come from though. Is that a new spec (written and approved by who?) or is that taken from the ver_config_id? (Also written and approved by who?)

**Comment by esune** [comment]
> I think for now, the list of claims and title is fine. No need for a description as that should be defined by the verifier on their own webpage. I'm not sure where the title will come from though. Is that a new spec (written and approved by who?) or is that taken from the ver_config_id? (Also written and approved by who?)

We (Digital Trust Team) review all proof-requests that are made available in the system so it's going to be us determining the correct title for proof-configurations.
