### ISSUE TITLE
A dead link in DemoInstructions.md

### ISSUE THREAD

**Issue by kzt-ysmr** [bcgov/vc-authn-oidc#68]
Hi.  Just a report.

Following [DemoInstructions.md](https://github.com/bcgov/vc-authn-oidc/blob/master/docs/DemoInstructions.md), I accessed to the following url by clicking a link in "Use the Verifiable Credential Identity Provider" section.
https://csb-audio.pathfinder.gov.bc.ca/

The service responded with the below error page (the HTTP status code was 503, not 404).
![image](https://user-images.githubusercontent.com/20537254/85196054-73b13d00-b312-11ea-930f-75b49709a006.png)
I'm not sure if this is temporary, but if not, we have to amend the link.

**Comment by swcurran** [comment]
We've been moving demos around.  Thanks for the note and sorry about the issue. We're looking at how to address this.
