### ISSUE TITLE
How Integration of SSI with OpenID is useful or optimal as compared to SSI without OpenID?

### ISSUE THREAD

**Issue by ankitkr1606** [bcgov/vc-authn-oidc#83]
I've read some research papers on SSI and SSI integration with OpenID and, as here SSI is integrated with openID. So can you tell me Why SSI integration with openID is optimal to SSI without openID?

**Comment by esune** [comment]
I am not sure I understand your question. Open ID Connect is a widely used standard and having an OIDC-compliant SSI authentication method allows for an easy integration of SSI/Verifiable Credentials in existing systems, without the need for "special" changes.

Whether you use an OIDC integration or not it will depend on a number of factors, including what you are trying to achieve and what type of ecosystem you are working with and need to support/integrate.

**Comment by esune** [comment]
Closing the issue, @ankitkr1606 feel free to reopen if further discussion is required.
