### ISSUE TITLE
Access_token received from the token endpoint "/vc/connect/token" is invalid  

### ISSUE THREAD

**Issue by dipghoshraj** [bcgov/vc-authn-oidc#84]
I was trying to receive the access token from the token endpoint then I have received this one in response 

`{"request":{"configuration":{"authorizationEndpoint":"https:\/\/controller.vc.identity.ky\/vc\/connect\/authorize","tokenEndpoint":"https:\/\/controller.vc.identity.ky\/vc\/connect\/token"},"clientId":"app-auth","nonce":"aeBgbM9fcpwQYk4EQxjOOf0JuXR1QB9k","grantType":"authorization_code","redirectUri":"net.openid.appauthdemo:\/oauth2redirect","authorizationCode":"95b50d0b-a995-4ea2-b360-70a663fecd98","additionalParameters":{}},"token_type":"Bearer","access_token":"invalid","id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImI1NDU3MDhhNjBlNzIyODJhZDU4NTFiYTk0YmQwYmY4IiwidHlwIjoiSldUIn0.eyJuYmYiOjE2MDA0MjIwMjEsImV4cCI6MTYwMDQzMjAyMSwiaXNzIjoiaHR0cHM6Ly9jb250cm9sbGVyLnZjLmlkZW50aXR5Lmt5IiwiYXVkIjoiYXBwLWF1dGgiLCJwcmVzX3JlcV9jb25mX2lkIjoidmVyaWZpZWQtZW1haWwiLCJhY3IiOiJ2Y19hdXRobiIsIm5vbmNlIjoiYWVCZ2JNOWZjcHdRWWs0RVF4ak9PZjBKdVhSMVFCOWsiLCJlbWFpbCI6Imxva2VuYXRoQGtsaXpvcy5jb20iLCJzdWIiOiJsb2tlbmF0aEBrbGl6b3MuY29tIiwiaWF0IjoxNjAwNDIyMDIxfQ.fvQG3mFQ-PYV7WUWiW2HjRMU228n6TL2ZCl5Tu8iWmt9V2dAVmH_s4kV2uF6pg20tqMx6pj6JzTI55MLnCkRvr0WhMh459850GiU_BK1q-_g_3CWFaHi1XNssQVJJ9L4ChGTqM41e2RKIpzGCgdIE1ZLfXOwQdx08H-35fTSxP_Zj3UEqYfayxHjhujsVKg7Y6v-wd6D1d_TH3CHaVRQBqDPVhU24y0_tex_gozXL-_UYCZ1KDuYDbLd1Djmk1TnA18m3wcdniBlDUzlLGDjfpO294PBJvO7py1h_WFRps-bZJvSdFDWyjfDpfXmOO9Jf9aEft2D2IC3ZB8HctTxtA","additionalParameters":{}}`

**So here the access token is invalid, after serching on the code i have found the the access token is hard-coded as invilid in the tokenEndpointResult.cs file line no. 71.** 

`await context.Response.WriteJsonAsync(
             new
                {
                    access_token = "invalid",
                    id_token = token,
                    token_type = "Bearer"
                });`

So, without this access_token I can't use the user-info endpoint, is there any way to access the user-info endpoint.

**Comment by swcurran** [comment]
@esune -- this seems weird.  Can you take a look, please?

**Comment by esune** [comment]
@dipghoshraj `vc-authn-oidc` does not have a userInfo endpoint implementation, since it is stateless (there is no user database).

**Comment by dipghoshraj** [comment]
@esune thanks for clearing my query, so to access protected resources at Resource Servers, we need to pass the access token for this. Any information related to this will be very helpful.

**Comment by esune** [comment]
@dipghoshraj you are right, `vc-authn-oidc` does not return an access token, it just returns an identity token.

I am unsure about the reason driving this choice and will have to further investigate on whether it is a missing feature or a limitation, however you should be able to achieve what you are describing by authenticating using `vc-authn-oidc` through an AIM system such as Keycloak acting as mediator. This way your OIDC authentication endpoints would be with Keycloak and `vc-authn-oidc` would just be an Identity Provider you can choose when authenticating.

**Comment by dipghoshraj** [comment]
Thank you @esune .
